<template>
    <div class="flex flex-col pt-6 pl-24 pr-24 pb-6 bg-white text-gray-900 border-2 rounded border-white">
        <div>
            <h2 class="text-center text-2xl font-semibold mb-10 text-gray-600 uppercase">My <span class="text-green-500">Blog</span></h2>
        </div>
        <div>
            <div class="flex flex-col pb-6" v-for="post in posts">
                <router-link :to="{name: 'blog'}" class="text-center text-lg text-green-500 hover:text-green-600 font-semibold tracking-wider text-xl pb-2">{{ post.title }}</router-link>
                <span class="text-center text-md text-gray-500 pb-2 tracking-normal"> by {{ post.author }} on {{ post.published_at }}</span>
                <span class="text-lg text-gray-500 pb-2 tracking-normal"> {{ post.summary }} </span>
            </div>
        </div>
    </div>
</template>

<script>
    export default {
        data() {
            return {
                posts: [
                    { title: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur, impedit. 1', summary: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid aperiam autem laboriosam nostrum possimus suscipit, velit. Ad adipisci aliquam animi commodi debitis doloribus eaque enim, eos est ex illo impedit incidunt ipsam maxime molestiae molestias nam natus neque nulla obcaecati officia, omnis quaerat quam repudiandae similique sint soluta sunt suscipit tempore temporibus tenetur veritatis voluptas voluptatum! Non odit sit ut voluptate. Adipisci aliquid aspernatur atque aut beatae consequatur, dolorem ea, facere harum inventore ipsa libero, molestias pariatur praesentium qui quibusdam suscipit velit? Ad esse nihil, officia perferendis quisquam quod tempore ut vel velit. Accusamus, ipsa labore laborum maiores necessitatibus nulla numquam optio porro provident quaerat quas quidem quod soluta velit voluptatum? Architecto dolor doloribus ducimus eaque incidunt natus reiciendis tenetur! Alias assumenda deserunt excepturi id, ipsum mollitia odit, praesentium quidem tempore totam ullam voluptas. Accusamus ad adipisci alias aliquid, earum eligendi maiores molestiae porro quidem repudiandae vel, voluptate voluptates! Laborum?', author: 'Davor Minchorov', published_at: 'September 19, 2019'  },
                    { title: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus, aliquam! 2', summary: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid aperiam autem laboriosam nostrum possimus suscipit, velit. Ad adipisci aliquam animi commodi debitis doloribus eaque enim, eos est ex illo impedit incidunt ipsam maxime molestiae molestias nam natus neque nulla obcaecati officia, omnis quaerat quam repudiandae similique sint soluta sunt suscipit tempore temporibus tenetur veritatis voluptas voluptatum! Non odit sit ut voluptate. Adipisci aliquid aspernatur atque aut beatae consequatur, dolorem ea, facere harum inventore ipsa libero, molestias pariatur praesentium qui quibusdam suscipit velit? Ad esse nihil, officia perferendis quisquam quod tempore ut vel velit. Accusamus, ipsa labore laborum maiores necessitatibus nulla numquam optio porro provident quaerat quas quidem quod soluta velit voluptatum? Architecto dolor doloribus ducimus eaque incidunt natus reiciendis tenetur! Alias assumenda deserunt excepturi id, ipsum mollitia odit, praesentium quidem tempore totam ullam voluptas. Accusamus ad adipisci alias aliquid, earum eligendi maiores molestiae porro quidem repudiandae vel, voluptate voluptates! Laborum?', author: 'Davor Minchorov', published_at: 'September 19, 2019' },
                    { title: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur, impedit. 3', summary: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid aperiam autem laboriosam nostrum possimus suscipit, velit. Ad adipisci aliquam animi commodi debitis doloribus eaque enim, eos est ex illo impedit incidunt ipsam maxime molestiae molestias nam natus neque nulla obcaecati officia, omnis quaerat quam repudiandae similique sint soluta sunt suscipit tempore temporibus tenetur veritatis voluptas voluptatum! Non odit sit ut voluptate. Adipisci aliquid aspernatur atque aut beatae consequatur, dolorem ea, facere harum inventore ipsa libero, molestias pariatur praesentium qui quibusdam suscipit velit? Ad esse nihil, officia perferendis quisquam quod tempore ut vel velit. Accusamus, ipsa labore laborum maiores necessitatibus nulla numquam optio porro provident quaerat quas quidem quod soluta velit voluptatum? Architecto dolor doloribus ducimus eaque incidunt natus reiciendis tenetur! Alias assumenda deserunt excepturi id, ipsum mollitia odit, praesentium quidem tempore totam ullam voluptas. Accusamus ad adipisci alias aliquid, earum eligendi maiores molestiae porro quidem repudiandae vel, voluptate voluptates! Laborum?', author: 'Davor Minchorov', published_at: 'September 19, 2019'  },
                    { title: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur, impedit. 4', summary: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid aperiam autem laboriosam nostrum possimus suscipit, velit. Ad adipisci aliquam animi commodi debitis doloribus eaque enim, eos est ex illo impedit incidunt ipsam maxime molestiae molestias nam natus neque nulla obcaecati officia, omnis quaerat quam repudiandae similique sint soluta sunt suscipit tempore temporibus tenetur veritatis voluptas voluptatum! Non odit sit ut voluptate. Adipisci aliquid aspernatur atque aut beatae consequatur, dolorem ea, facere harum inventore ipsa libero, molestias pariatur praesentium qui quibusdam suscipit velit? Ad esse nihil, officia perferendis quisquam quod tempore ut vel velit. Accusamus, ipsa labore laborum maiores necessitatibus nulla numquam optio porro provident quaerat quas quidem quod soluta velit voluptatum? Architecto dolor doloribus ducimus eaque incidunt natus reiciendis tenetur! Alias assumenda deserunt excepturi id, ipsum mollitia odit, praesentium quidem tempore totam ullam voluptas. Accusamus ad adipisci alias aliquid, earum eligendi maiores molestiae porro quidem repudiandae vel, voluptate voluptates! Laborum?', author: 'Davor Minchorov', published_at: 'September 19, 2019'  },
                    { title: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur, impedit. 5', summary: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid aperiam autem laboriosam nostrum possimus suscipit, velit. Ad adipisci aliquam animi commodi debitis doloribus eaque enim, eos est ex illo impedit incidunt ipsam maxime molestiae molestias nam natus neque nulla obcaecati officia, omnis quaerat quam repudiandae similique sint soluta sunt suscipit tempore temporibus tenetur veritatis voluptas voluptatum! Non odit sit ut voluptate. Adipisci aliquid aspernatur atque aut beatae consequatur, dolorem ea, facere harum inventore ipsa libero, molestias pariatur praesentium qui quibusdam suscipit velit? Ad esse nihil, officia perferendis quisquam quod tempore ut vel velit. Accusamus, ipsa labore laborum maiores necessitatibus nulla numquam optio porro provident quaerat quas quidem quod soluta velit voluptatum? Architecto dolor doloribus ducimus eaque incidunt natus reiciendis tenetur! Alias assumenda deserunt excepturi id, ipsum mollitia odit, praesentium quidem tempore totam ullam voluptas. Accusamus ad adipisci alias aliquid, earum eligendi maiores molestiae porro quidem repudiandae vel, voluptate voluptates! Laborum?', author: 'Davor Minchorov', published_at: 'September 19, 2019'  },
                    { title: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur, impedit. 6', summary: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid aperiam autem laboriosam nostrum possimus suscipit, velit. Ad adipisci aliquam animi commodi debitis doloribus eaque enim, eos est ex illo impedit incidunt ipsam maxime molestiae molestias nam natus neque nulla obcaecati officia, omnis quaerat quam repudiandae similique sint soluta sunt suscipit tempore temporibus tenetur veritatis voluptas voluptatum! Non odit sit ut voluptate. Adipisci aliquid aspernatur atque aut beatae consequatur, dolorem ea, facere harum inventore ipsa libero, molestias pariatur praesentium qui quibusdam suscipit velit? Ad esse nihil, officia perferendis quisquam quod tempore ut vel velit. Accusamus, ipsa labore laborum maiores necessitatibus nulla numquam optio porro provident quaerat quas quidem quod soluta velit voluptatum? Architecto dolor doloribus ducimus eaque incidunt natus reiciendis tenetur! Alias assumenda deserunt excepturi id, ipsum mollitia odit, praesentium quidem tempore totam ullam voluptas. Accusamus ad adipisci alias aliquid, earum eligendi maiores molestiae porro quidem repudiandae vel, voluptate voluptates! Laborum?', author: 'Davor Minchorov', published_at: 'September 19, 2019'  },
                ]
            }
        },
    }
</script>

